import { Star } from "lucide-react";
const data = [
  {
    id: "1d6a3f05-29af-4944-82da-9e4720bbb114",
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    images: {
      black: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      white: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      red: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    },
    title: "Nike Air Monarch IV",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    category: "sneakers",
    color: ["red", "white", "black"],
  },
  {
    id: "ebc8be07-dcf3-4bd0-a31f-f8ce6bd2fb1c",
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "8dea6493-7301-4de0-bb2c-6c1e072ad166",
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "c9d2e297-6770-4641-baf9-9362491c8f2c",
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "c3573b9c-f2ac-4f99-bee1-48ccc08bd29a",
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    category: "flats",
    color: ["red", "white", "blue"],
  },
  {
    id: "c457e0d8-7a19-46bd-8031-3b5d246021f9",
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    category: "flats",
    color: ["red", "white", "blue"],
  },
  {
    id: "04b74f00-c363-416b-b820-449a9804edcb",
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    category: "flats",
    color: ["red", "white", "blue"],
  },
  {
    id: "ea51dd1f-6e7f-4982-9fb0-a62190e655dd",
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "e5f6844f-bd59-412b-b18d-385ba0163072",
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "2667c0c6-ffed-4fe3-89a1-699b3effa7ea",
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "39e0f4ac-3571-4c0b-ad5c-dbd049fa224d",
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "230830a2-c98a-4e60-93af-16c65b1a6624",
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "ba1cd573-0cea-452e-9c27-1032b0256768",
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "7a3de75c-c237-4138-a5fc-4cef6a84464d",
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "437dd5f9-78c0-4612-998a-36ed0856c67d",
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "bfc3c08b-7aef-4dc5-a00d-4e3f06d727a8",
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    category: "flats",
    color: ["red", "white", "blue"],
  },
  {
    id: "a451df3a-2486-4944-9d46-bc158c7f75da",
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    category: "sandals",
    color: ["red", "white", "blue"],
  },
  {
    id: "cc6ff9b2-70ba-4992-8127-4ad37e4015d8",
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    category: "sandals",
    color: ["red", "white", "blue"],
  },
  {
    id: "3dd73ca6-2ed5-4fa0-91be-2773802bbb81",
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Nike",
    category: "sandals",
    color: ["red", "white", "blue"],
  },
  {
    id: "59619c61-61bc-4775-babd-3b1ee5754261",
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    category: "heels",
    color: ["red", "white", "blue"],
  },
  {
    id: "3edb8dc9-1e41-4577-9bd9-79e2804e8a1b",
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "puma",
    category: "heels",
    color: ["red", "white", "blue"],
  },
  {
    id: "d5550e6a-246e-45e1-8e58-276b060b6951",
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    category: "heels",
    color: ["red", "white", "blue"],
  },
  {
    id: "183d96ed-b81a-42af-8fca-e39812d56e7f",
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    category: "sneakers",
    color: ["red", "white", "blue"],
  },
  {
    id: "d86efac9-5227-4000-9881-7a29ca3ba773",
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    category: "heels",
    color: ["red", "white", "blue"],
  },
  {
    id: "2cd304cd-25c0-438c-931f-eb0e9e68b320",
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    category: "heels",
    color: ["red", "white", "blue"],
  },
  {
    id: "45a97633-07c2-4292-be59-72566767c3b3",
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Adidas",
    category: "heels",
    color: ["red", "white", "blue"],
  },
  {
    id: "f19ede50-79a6-46d6-b81b-7bd0727c1fc7",
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,

    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    category: "heels",
    color: ["red", "white", "blue"],
  },
  {
    id: "9c395cb9-23da-4258-8c5b-c9a8c6a8dd4e",
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    size: ["sm", "md", "l", "xl", "xxl"],
    star: <Star />,
    star: <Star />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    category: "flats",
    color: ["red", "white", "blue"],
  },
];

export default data;
